name: geog0133_env

channels:
    - jgomezdans

dependencies:
    - jupyterlab=1.0.0
    - notebook
    - nbconvert
    - ipykernel
    - ipywidgets
    - ipyleaflet
    - widgetsnbextension
    - matplotlib
    - pandas
    - python>=3.6
    - gomezengine
    - gdal>=2.3.0
    - tqdm
    - libgdal>=2.3.0
    - jupyter_contrib_nbextensions
    - widgetsnbextension
