name: ghana_ucl
channels:
    - conda-forge
dependencies:
    - jupyterlab
    - dask
    - notebook
    - nbconvert
    - ipykernel
    - ipywidgets
    - ipyleaflet
    - widgetsnbextension
    - matplotlib
    - pandas
    - scipy
    - python>=3.8
    - gdal>=3.0
    - tqdm
    - libgdal>=3.0
    - jupyter_contrib_nbextensions
    - widgetsnbextension
    - pip
    - pip:
        - pcse
        - git+https://github.com/jgomezdans/GomezEngine
