name: geog0133_env

dependencies:
    - jupyterlab
    - notebook
    - nbconvert
    - ipykernel
    - ipywidgets
    - ipyleaflet
    - widgetsnbextension
    - matplotlib
    - pandas
    - python>=3.6
    - gdal>=2.3.0
    - tqdm
    - libgdal>=2.3.0
    - jupyter_contrib_nbextensions
    - widgetsnbextension
