name: geog0133_env

channels:
    - jgomezdans

dependencies:
    - jupyterlab=0.34.0
    - nodejs=8.9
    - notebook=5.6
    - nbconvert=5.3
    - ipykernel=4.7
    - ipywidgets=7.3
    - ipyleaflet=0.9
    - widgetsnbextension=3.3
    - matplotlib=2.1
    - pandas=0.20
    - python=3.6
    - gomezengine
    - gdal>=2.3.0
    - tqdm
    - libgdal>=2.3.0
    - jupyter_contrib_nbextensions
    - widgetsnbextension
