#!/bin/bash

# Install a JupyterLab extension for demonstration purposes
jupyter labextension install @jupyterlab/geojson-extension jupyterlab-drawio
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter trust *.ipynb
